---
- name: Create swap.conf.d directory
  ansible.builtin.file:
    path: /etc/systemd/swap.conf.d
    state: directory
    owner: root
    mode: "0755"

- name: Check existing configuration files
  ansible.builtin.find:
    paths: /etc/systemd/swap.conf.d
    patterns: "*.conf"
  when: systemd_swap_cleanup
  register: existing_config

- name: Remove existing configuration files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ existing_config.files }}"
  when: systemd_swap_cleanup
  notify: Restart systemd-swap

- name: Generate configuration files
  ansible.builtin.template:
    src: swap.conf.d.j2
    dest: "/etc/systemd/swap.conf.d/{{ item.key }}.conf"
    owner: root
    mode: "0644"
  loop: "{{ systemd_swap_conf_d | dict2items }}"
  notify: Restart systemd-swap
